#!/usr/bin/env bash

mc_port=25566

if [ -z "$DROPBOX_API_TOKEN" ]; then
  echo "Please specify your dropbox key to sync your data!"
  exit 1
fi

# Do save dropbox config file
echo "OAUTH_ACCESS_TOKEN=$DROPBOX_API_TOKEN" > /app/.dropbox_uploader

# Do get server files if there is
bin/dropbox download /backup/sv.zip

# Do an inline sync first, then start the background job
echo "Starting dropbox sync..."
eval "while true; do sleep 45; zip -r sv.zip panel/; bin/dropbox upload sv.zip /backup/sv.zip; rm sv.zip; done &"
sync_pid=$!

trap "kill $ngrok_pid $main_pid $sync_pid" SIGTERM
trap "kill -9 $ngrok_pid $main_pid $sync_pid; exit" SIGKILL
