#!/usr/bin/env bash

if [ -z "$DROPBOX_API_TOKEN" ]; then
  echo "Please specify your dropbox key to sync your data!"
  exit 1
fi

# Do save dropbox config file
echo "OAUTH_ACCESS_TOKEN=$DROPBOX_API_TOKEN" > /app/.dropbox_uploader

# Do get server files if there is
./dropbox download /mcgg/sv.zip 
unzip -o sv.zip
rm sv.zip

# Do an inline sync first, then start the background job
echo "-----> Starting dropbox sync..."
while true; do
    sleep 45
    ./dropbox delete /mcgg/sv.zip
    zip -r sv.zip panel/
    ./dropbox upload sv.zip /mcgg/sv.zip
    rm sv.zip
done
sync=$!

trap "zip -r sv.zip panel/; ./dropbox upload sv.zip /mcgg/sv.zip; rm sv.zip" SIGTERM
trap "kill -10 $sync; exit" SIGKILL
