#!/usr/bin/env bash
echo "!----- Syncing files to Dropbox -----!"
./dropbox upload /app/panel/data/users/* /mcgg/users
sleep 3
zip -r backup.zip /app/server/*
sleep 3
./dropbox upload backup.zip /mcgg/server
