#!/usr/bin/env bash
echo "!----- Syncing files to Dropbox -----!"
./dropbox upload /app/panel/data/users/* /mcgg/users/
sleep 3
zip -r backup.zip server/*
sleep 3
./dropbox upload backup.zip /mcgg/server
rm backup.zip
